export const WRITE_STAT = "WRITE_STAT";
export const READ_STAT = "READ_STAT";
export const WRITE_MONEY_STAT = "WRITE_MONEY_STAT";

export const READ_BOX_STAT = "READ_BOX_STAT";
export const WRITE_BOX_STAT = "WRITE_BOX_STAT";

export const FETCH_COMPANIES = "FETCH_COMPANIES";
export const NEW_COMPANY = "NEW_COMPANY";
export const FETCH_ONE_COMPANY = "FETCH_ONE_COMPANY";
export const WRITE_COMPANY = "WRITE_COMPANY";
export const UPDATE_COMPANY_SUCCEDDED = "UPDATE_COMPANY_SUCCEDDED";
export const UPDATE_COMPANY_FAILED = "UPDATE_COMPANY_FAILED";
export const DELETE_COMPANY_SUCCEDDED = "DELETE_COMPANY_SUCCEDDED";
export const DELETE_COMPANY_FAILED = "DELETE_COMPANY_FAILED";

export const FETCH_LOAN = "FETCH_LOAN";
export const NEW_LOAN = "NEW_LOAN";
export const FETCH_ONE_LOAN = "FETCH_ONE_LOAN";

export const USER_LOGGED = "USER_LOGGED";
export const ADD_USER = "ADD_USER";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USERS = "FETCH_USERS";
export const NEW_USER = "NEW_USER";

export const FETCH_OFFERS = "FETCH_OFFERS";
export const NEW_OFFER = "NEW_OFFER";

export const FETCH_CONTENTS = "FETCH_CONTENTS";
export const NEW_CONTENT = "NEW_CONTENT";
export const FETCH_ONE_CONTENT = "FETCH_ONE_CONTENT";

export const FETCH_POSTS = "FETCH_POSTS";
export const NEW_POST = "NEW_POST";

export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";

//Authentication
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
